// Generated by LispyScript v0.3.6
console.log("LOADED!");
var macros = function() {
    return [
        ((true === ({
                "key": "value"
            } === {
                "key": "value"
            })) ?
            ("Passed - " + "(field <key> <value>)") :
            ("Failed - " + "(field <key> <value>)"))
    ];
};
console.log((function(groupname,desc) {
    var start = new Date(),
        tests = groupname(),
        passed = 0,
        failed = 0;
    (tests).forEach(function(elem) {
        return (elem.match(/^Passed/) ?
            ++passed :
            ++failed);
    });
    return [["\n",desc,"\n",start,"\n\n"].join(''),(tests).reduce(function(___memo,elem,index) {
        return (___memo + [elem,"\n"].join(''));
    },""),"\nTotal tests ",tests.length,"\nPassed ",passed,"\nFailed ",failed,"\nDuration ",(new Date() - start),"ms\n"].join('');
})(macros,"LispyScript Testing"));
